### ISSUE TITLE
JSON Serialization: Performance Benchmark among Gems

### ISSUE THREAD

**Issue by fadlinurhasan** [id-ruby/talks#4]
Talk Title: JSON Serialization: Performance Benchmark among Gems

Length: 15 - 20 Min.

Description (Long description to explain what your talk is all about)
Nowdays, web services with API endpoint are popular and massive, Rails also become one of the top options to build application. But how about performance inside rails and their JSON Serialization Gems? Is there any fastest json serialization gem and is it massively affect to your apps? or You can easily choose whichever gem and believe it already fast enough. I tried to benchmark those gems and wanna share about Json Serialization and their performance benchmark.

Abstract (Short description under 140 characters)
Knowing which better json serialization gems and is it really matter for your apps?

**Comment by giosakti** [comment]
This talk will be delivered on our February 2019 meetup at KMK office

**Comment by firewalker06** [comment]
Talk delivered.
