### ISSUE TITLE
5 Metaprogramming tips in Ruby

### ISSUE THREAD

**Issue by opan** [id-ruby/talks#5]
Talk Title: 5 Metaprogramming tips in Ruby
Length: around 15 - 20 mins
Description:
How does metaprogramming in Ruby looks like? Well in this talk I will talk about tips about metaprogramming in Ruby, and hopefully, give more understanding about what is metaprogramming in Ruby for people that just start their journey in Ruby language.
Short description:
What is metaprogramming? Ever wonder how is method missing in processed by Ruby?

**Comment by giosakti** [comment]
This talk will be delivered on our February 2019 meetup at KMK office

**Comment by firewalker06** [comment]
Talk delivered.
