### ISSUE TITLE
Things I Wish I Knew Before I Started to Code Ruby

### ISSUE THREAD

**Issue by hezbymuhammad** [id-ruby/talks#6]
Please fulfill the following information to submit your talk:

1. Things I Wish I Knew Before I Started to Code Ruby
2. 30 min
3. This talk is about my experience as Ruby developer for the past 2 years and things I wish I knew about Ruby concept when I started to code Ruby. It's about variables, lexical scope, metaclass, and syntactic sugar.
4. Ruby has a lot of magic. In fact, you don't have to understand the basic principles of Ruby in order to use Ruby. However, at some part of your life as Ruby developer, knowing how things work beyond the magic is necessary. This talk is about some of Ruby basic concept which often missed to understand such as variable, lexical scope, metaclass, and syntactic sugar.

**Comment by firewalker06** [comment]
Delivered in https://www.meetup.com/id-ruby/events/259186023/
