### ISSUE TITLE
There was Once when My Job Interview Turned Into Open Source Contribution

### ISSUE THREAD

**Issue by fudanchii** [id-ruby/talks#7]
There was Once when My Job Interview Turned Into Open Source Contribution

Length: 15-20 minutes

This is a story of my experience interviewing at certain IT company. It's turned out some part of the journey end up as a contribution to open source project. Will discuss about aspirations to contribute to open source project, ruby programming language, ruby FFI, and a small bit of cryptography.

abstract: Where to start contributing to open source project? It could be from anywhere, perhaps from your next job interview.

**Comment by firewalker06** [comment]
Delivered in https://www.meetup.com/id-ruby/events/259186023/

**Comment by fudanchii** [comment]
Here's the slide for the presentation, in case anyone interested: https://slides.com/nurahmadie/once-upon-oss#/ 🙏
