### ISSUE TITLE
Level UP!

### ISSUE THREAD

**Issue by groky** [id-ruby/talks#8]
Please fulfill the following information to submit your talk:

1. Level UP!
2. 20mins
3. Sometimes it can be hard to up your game and get to the next level of expertise. My story is like this
4. For 10 years I bounced around from job to job because I was afraid that people would discover that I wasn’t as good as I thought. I wasn’t a bad developer. I knew I was missing something - something everyone else seemed to have. I just didn’t know what it was...
[Level UP!.pdf](https://github.com/id-ruby/talks/files/3017686/Level.UP.pdf)

**Comment by firewalker06** [comment]
Delivered in https://www.meetup.com/id-ruby/events/259186023/
